### ISSUE TITLE
Add CI bot configuration for pre-commit

### ISSUE THREAD

**Issue by dokempf** [ssciwr/py4dgeo#11]
This is a new feature of `pre-commit` that will allow us to enforce e.g. code formatting etc.

**Comment by lkeegan** [comment]
https://pre-commit.ci/ is one-click setup and works great - except that I found that clang-format didn't work.
This ci job basically does the same thing: https://github.com/ssciwr/hammingdist/blob/master/.github/workflows/ci.yml#L47

**Comment by dokempf** [comment]
I guess the clang-format issue is because the clang-format `pip` package is not available on all platforms and therefore the hook does not specify the dependency on `clang-format` in https://github.com/pocc/pre-commit-hooks/blob/master/.pre-commit-hooks.yaml#L11 Luckily, this will be fixed when the packaging issue in https://github.com/mgevaert/clang-format-wheel/issues/4 is fully resolved.

**Comment by lkeegan** [comment]
very nice! I look forward to deleting my format ci job once this is available :-)
I came across this repo a while ago which might be a helpful reference in terms of building older versions on the various platforms: https://github.com/muttleyxd/clang-tools-static-binaries

**Comment by dokempf** [comment]
Pre-commit CI is enabled and working.
