### ISSUE TITLE
Add median and interquartile range as alternative uncertainty measure

### ISSUE THREAD

**Issue by dokempf** [ssciwr/py4dgeo#124]
Mentioned in #84.

**Comment by dokempf** [comment]
This brings up an interesting question: Currently the fields of the uncertainty data structure are named `lodetection` and `stddev1`. Should we use a better name for the latter that does imply it being a standard deviation? @kathapand

**Comment by kathapand** [comment]
Good point - a suitable, more general name would be `spread`, which can be expressed by both standard deviation or interquartile range

**Comment by dokempf** [comment]
`variation` might also be possible, I guess

**Comment by kathapand** [comment]
yes, equally fine by me
