### ISSUE TITLE
Add parameter to specify which point cloud is used for normal calculation

### ISSUE THREAD

**Issue by kathapand** [ssciwr/py4dgeo#38]
During M3C2 distance calculation, normals need to be calculated for each core point to derive the surface orientation.
Normals can be computed considering different points in the neighborhood of the core point:
(a) using neighboring points in the core points, i.e. disregarding the input point cloud epochs, or 
(b) using neighboring points of an epochs cloud (the first epoch or any other in the available epochs).

Currently, normals are calculated for using the first epoch specified in `py4dgeo.M3C2()`.
Selection by the user could be enabled by implementing an additional parameter `cloud_for_normals` where the index of the epoch to use is specified, or -1 to use the core points, i.e.:
`cloud_for_normals = -1` uses the core points for normals calculation
`cloud_for_normals = 0 ` uses the point cloud of the first specified epoch (`default`; corresponds to current implementation)
`cloud_for_normals = 1` uses the points of the second specified epoch

**Comment by dokempf** [comment]
#59 implements this, but in a slightly more generic way. You may specify any epoch (object of type `Epoch`) or point cloud (`np.ndarray` of correct shape) to use for normal calculation. If a point cloud is given, a search tree for that cloud is constructed. If an epoch is given, the search tree is reused. If the parameter is omitted, the first epoch is used.
