### ISSUE TITLE
Change M3C2 parameter names to be more intuitive

### ISSUE THREAD

**Issue by kathapand** [ssciwr/py4dgeo#84]
The current parameter names (i) `scales` for normal estimation radii and (ii) `radii` for averaging the point position in `py4dgeo.M3C2()` can be easily confused. 

More suitable and intuitive names could be: `normal_radii` and `cyl_radii`

To be more general, `search_radii` could be used for `cyl_radii`. But as no other geometry is to be expected, the more specific term would be preferred.

**Comment by dokempf** [comment]
As discussed today, I will happily implement any renamings you have, but I would prefer to the them all at once. Please give me a go when you have discussed all the renamings.

**Comment by kathapand** [comment]
Suggestion for M3C2 parameter names based on original/CloudCompare parameters (see also attached file [m3c2_params_names.txt](https://github.com/ssciwr/py4dgeo/files/7870898/m3c2_params_names.txt)
):

| CloudCompare  | py4dgeo | py4dgeo-CC | Description |
| ------------- | ------------- | ------------- | ------------- |
| `NormalScale`  | `normal_radii`  | `normalscale` | Search radius for normals estimation (currently `scales`)  |
| `NormalMode`  |  | | _WHAT IS THIS?_  |
| `NormalUseCorePoints`  |   |  |   |
| `NormalPreferedOri`  | NA  | NA | Specification of preferred normals orientation, direction in py4dgeo  |
| `SearchScale`  | `cyl_radii` (or `search_radii`?)  | `searchscale` | Radius of cylinder used to search points for position averaging (currently `radii`)|
| `SearchDepth`  |  `cyl_length` | `searchdepth` |  Maximum length of cylinder to search for points in compared cloud (currently `max_cylinder_length`) |
| `RegistrationError`  |  `reg_error` | `registrationerror` | Registration error to be used in level of detection determination (not yet implemented in py4dgeo)  |
| `UseSinglePass4Depth`  | ? | `usesinglepath4depth `| This is the cylinder option, which we are currently testing (and probalby most CC M3C2 users are not aware it can be set)  |
| `UseMedian`  | ? (`use_median`) | `usemedian` | if True, use median instead of mean in uncertainty calculation; to be discussed if we implement it  |
| `UseMinPoints4Stat`  |  ? (`min_points_stat`) | `useminpoints4stat` | Number of points (minimum) to use for statistics calculation, else NaN; do we implement it as parameter?  |

**Comment by kathapand** [comment]
Thanks for the review @lwiniwar 

Below the adapted table for updating paramter names, based on the following considerations of above points:

1. Pre-computed normals can be input as `directions` (with same shape as corepoints). To make the user aware that normals are not calculated by py4dgeo-m3c2, a Warning should be raised, e.g. if the user specified `normal_radii` or other normals-related parameters.
2. We may use the parameter name `robust_aggr` to switch from _mean and standard deviation_ (default, `robust_aggr=False`) to _median and interquartile range_ (`robust_aggr=True`)
3. We remove `minPoints4Stat` as obsolete
4. We use `max_distance` for the maximum (half) cylinder length to avoid ambiguity
5. Typo corrected

| CloudCompare  | py4dgeo | py4dgeo-CC | Description |
| ------------- | ------------- | ------------- | ------------- |
| `NormalScale`  | `normal_radii`  | `normalscale` | Search radius for normals estimation (currently `scales`)  |
| `NormalMode`  |  | | _not required_ but see bullet (1) above |
| `NormalUseCorePoints`  |   |  | Use core points for normals or epoch points; in py4dgeo this is explicitly specified (e.g. epoch1), not boolean  |
| `NormalPreferedOri`  | NA  | NA | Specification of preferred normals orientation, direction in py4dgeo  |
| `SearchScale`  | `cyl_radii` (or `search_radii`?)  | `searchscale` | Radius of cylinder used to search points for position averaging (currently `radii`)|
| `SearchDepth`  |  `max_distance` | `searchdepth` |  Maximum length of cylinder to search for points in compared cloud (currently `max_cylinder_length`) |
| `RegistrationError`  |  `reg_error` | `registrationerror` | Registration error to be used in level of detection determination (not yet implemented in py4dgeo)  |
| `UseSinglePass4Depth`  | ? | `usesinglepass4depth `| This is the cylinder option, which we are currently testing (and probably most CC M3C2 users are not aware it can be set); will be decided if parameter should be available  |
| `UseMedian`  | `robust_aggr` | `usemedian` | if True, use median and interquartile range instead of mean and standard deviation in distance and uncertainty calculation; see bullet (2) above |
| `UseMinPoints4Stat`  |  NA | NA | Number of points (minimum) to use for statistics calculation; not needed, see bullet (3) above  |
